<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class NewsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::insert("INSERT INTO `news` (`id`, `title`, `desc`, `slug`, `view`, `user_id`, `created_at`, `updated_at`) VALUES (1, 'AJAK MASYARAKAT TAAT MEMBAYAR PAJAK', '<div>BALIKPAPAN – Kepala Badan Pendapatan Daerah Prov Kaltim Ismiati mendampingi Anggota Dewan Perwakilan Rakyat Daerah (DPRD) Kaltim Mimi Meriami Pane, melakukan Sosialisasi Peraturan Daerah di Balikpapan. Kegiatan dilaksanakan di Sumber Rejo V, Jumat (24/6)</div><div>Sosialisasi tersebut diselenggarakan guna memberikan edukasi kepada masyarakat mengenai Perda Kaltim Nomor 1/2019 tentang Perubahan Kedua Atas Peraturan Daerah Nomor 1/2011 tentang Pajak Daerah.</div><div>Ismiati mengatakan, Pajak Daerah memberikan kontribusi cukup besar dalam Pendapatan Asli Daerah. Sektor ini juga menyumbang sekitar 39 persen dalam postur APBD Kaltim.</div><div>“Pajak Daerah ini terdiri dari Pajak Kendaraan Bermotor (PKB), Bea Balik Nama Kendaraan Bermotor (BBNKB), Pajak Bahan Bakar Kendaraan Bermotor (PBBKB), Pajak Air Permukaan (PAP), dan Pajak Rokok,” papar Ismi.</div><div>Dalam proses pembayaran pajak, kata dia, Bapenda telah memberikan beragam kemudahan.</div><div>Selain memperluas jangkauan kantor layanan, Bapenda juga membuka jalur pembayaran baru memanfaatkan teknologi digital. Ismi menyebutkan layanan seperti E-Samsat Gojek, E-Samsat Tokopedia, E-Samsat Paykaltimtara, dan E-Dalam Genggaman Bhabin untuk pembayaran PKB.</div><div>“Dengan beragamnya layanan Bapenda, kami berharap masyarakat dapat taat membayarkan pajak,” sebut dia.</div><div>Sementara itu, Mimi menegaskan pentingnya masyarakat untuk membayar pajak dikarenakan penerimaan dari sektor itu nantinya juga akan digunakan untuk pembangunan daerah seperti pembangunan jalan, jembatan, dan infrastruktur lainnya.</div>', 'ajak-masyarakat-taat-membayar-pajak', 0, 1, '2022-12-15 08:22:02', '2022-12-15 08:22:02');");
        DB::insert("INSERT INTO `news` (`id`, `title`, `desc`, `slug`, `view`, `user_id`, `created_at`, `updated_at`) VALUES (2, 'Gubernur Presentasikan Simpator di KIPP 2022', '<div>SAMARINDA – Kompetisi Inovasi Pelayanan Publik (KIPP) 2022 gelaran Kementerian PANRB memasuki tahap presentasi dan wawancara. Jumat (8/7), Gubernur Kaltim H Isran Noor menjadi presenter utama didampingi Kepala Bapenda Kaltim Hj Ismiati serta tenaga IT Bapenda Ricky Hendrayana.</div><div>Gubernur memaparkan inovasi Sistem Informasi Monitoring Pajak Kendaraan Bermotor (Simpator) yang masuk menjadi Top Finalis. Inovasi ini terus melaju mengungguli ribuan inovasi yang masuk dalam kompetisi tersebut.</div><div>“Menjalankan pemerintahan inovatif merupakan keharusan. Sebab, inovasi menjadi solusi atas berbagai persoalan dalam melayani masyarakat,” sebut Gubernur.</div><div>Hadirnya Simpator merupakan komitmen pemerintah daerah membangun kepercayaan masyarakat untuk taat membayar pajak.</div><div>“Simpator mendorong partisipasi masyarakat dalam membayar pajak. Terdapat peningkatan penerimaan PKB tahun 2018 yang tumbuh 7,78 persen dengan realisasi Rp 871,87 miliar. Sementara, pada tahun 2019 penerimaan PKB sebesar Rp 1,007 triliun atau tumbuh 15,53 persen dari tahun sebelumnya,” papar Isran dihadapan Tim Penilai Independen yang diketuai Prof. Dr. JB Kristiadi.</div><div>Sementara itu, Kepala Bapenda Kaltim mengatakan Simpator merupakan wujud transparansi Bapenda dalam menyajikan informasi.</div><div>“Baik mengenai informasi pajak kendaraan bermotor sampai dengan realisasi penerimaan PKB dan BBNKB bisa diakses siapa saja dan di mana saja,” kata dia.</div>', 'gubernur-presentasikan-simpator-di-kipp-2022', 0, 1, '2022-12-15 08:23:22', '2022-12-15 08:23:22');");
        DB::insert("INSERT INTO `news` (`id`, `title`, `desc`, `slug`, `view`, `user_id`, `created_at`, `updated_at`) VALUES (3, 'Kabapenda Pimpin Rapat Pembahasan NJKB', '<div>SAMARINDA – Kepala Badan Pendapatan Daerah Prov Kaltim Hj Ismiati memimpin rapat mengenai pembahasan Nilai Jual Kendaraan Bermotor (NJKB) dan Rapergub NJKB sebelum tahun 2022, Senin (18/7). Hal ini sesuai dengan Peraturan Menteri Dalam Negeri (Permendagri) Nomor 82/2022 tentang Dasar Pengenaan Pajak Kendaraan Bermotor, Bea Balik Nama Kendaraan Bermotor, dan Pajak Alat Berat 2022.</div><div>Dalam beleid tersebut, terdapat 2.526 tipe kendaraan yang harus disesuaikan NJKB-nya. Selain itu adanya pengatuan mengenai penetapan Nilai Jual Alat Berat (NJAB) dan perubahan bobot kendaraan jenis truk yang asalnya 1.3 menjadi 1.4.</div><div>“Guna menindaklanjutinya kami akan mengusulkan penyusunan peraturan gubernur mengenai NJKB karena penerbitannya diberi waktu selama 30 hari sejak permendagri diresmikan,” kata dia.</div>', 'kabapenda-pimpin-rapat-pembahasan-njkb', 0, 1, '2022-12-15 08:24:25', '2022-12-15 08:24:25');");
        DB::insert("INSERT INTO `news` (`id`, `title`, `desc`, `slug`, `view`, `user_id`, `created_at`, `updated_at`) VALUES (4, 'KABAPENDA HADIRI RAPAT KERJA KOMISI II DPRD KALTIM DONGKRAK PAD DARI SEKTOR BUMD', '<div>BALIKPAPAN – Komisi II Dewan Perwakilan Rakyat Daerah (DPRD) Provinsi Kalimantan Timur (Kaltim) menggelar rapat kerja bersama Pemprov Kaltim dan seluruh BUMD di Prov Kaltim, Minggu (24/7).</div><div>Rapat dipimpin oleh Wakil Ketua DPRD yakni Muhammad Samsun, Sigit Wibowo, dan Seno Aji serta didampingi Ketua Komisi II DPRD Kaltim Nidya Listiyono.</div><div>Peningkatan Pendapatan Asli Daerah (PAD) melalui kinerja pendapatan BUMD di Benua Etam jadi agenda rapat kali ini.</div><div>Kepala Bapenda Kaltim Hj Ismiati turut hadir sebagai undangan. Ismi memaparkan laporan tentang realisasi pendapatan dari perusahaan daerah dan BUMD terkait dengan target 2022, serta rencana pendapatan dari perusahaan daerah dan BUMD untuk tahun 2023.</div><div>Pertemuan dimaksudkan untuk mendorong optimalisasi kinerja perusahaan daerah dan BUMD.</div><div>“Hal tersebut untuk mendongkrak pendapatan asli daerah guna pembiayaan pembangunan,” kata Ismi.</div>', 'kabapenda-hadiri-rapat-kerja-komisi-ii-dprd-kaltim-dongkrak-pad-dari-sektor-bumd', 0, 1, '2022-12-15 08:25:52', '2022-12-15 08:25:52');");
        DB::insert("INSERT INTO `news` (`id`, `title`, `desc`, `slug`, `view`, `user_id`, `created_at`, `updated_at`) VALUES (5, 'Sosialisasi Perda Pajak, Ajak Masyarakat Berkontribusi Bangun Daerah', '<div>ANGGANA, KUKAR – Badan Pendapatan Daerah Prov Kaltim menemani langkah Legislator Kaltim di Karang Paci melakukan Sosialisasi Peraturan Daerah Nomor 1/2019 tentang Perubahan Kedua Atas Peraturan Daerah Nomor 1/2011 tentang Pajak Daerah.</div><div>Kepala Bapenda Prov Kaltim Hj Ismiati hadir sebagai narasumber dalam kegiatan yang dilaksanakan di Balai Pertemuan Umum (BPU) Desa Sidomulyo, Kecamatan Anggana, Kukar, pada Sabtu (30/7).</div><div>Ismi mengatakan sejumlah pajak menjadi tanggung jawab Pemprov Kaltim. Yakni Pajak Kendaraan Bermotor (PKB), Bea Balik Nama Kendaraan Bermotor (BBNKB), Pajak Bahan Bakar Kendaraan Bermotor (PBBKB), Pajak Air Permukaan (PAP), dan Pajak Rokok.</div><div>“Kelima pajak inilah yang menjadi bagian dari Pajak Daerah yang nantinya menjadi salah satu sumber kekuatan fiskal daerah,” jelasnya.</div><div>Dia menerangkan, sekarang ini pembayaran pajak bisa dilakuan secara online melalui aplikasi yang sudah disiapkan oleh pemerintah. “Lewat sosialisasi ini saya ingin masyarakat tahu, bahwa membayar pajak itu tidak harus ke kantor pajak. Tapi cukup dengan membuka aplikasinya dan bisa langsung mengetahui nominal dari pajak tersebut,” kata Ismi.</div><div>Sementara itu, Anggota DPRD Kaltim Rima Hartati mengatakan tujuan dari sosialisasi ini antara lain agar masyarakat memahami perda yang diterbitkan, kemudian bagi wajib pajak memiliki kesadaran untuk menuntaskan kewajiban mereka membayar pajak, karena hasil pajak akan digunakan untuk berbagai bidang pembangunan.</div><div>Jika makin banyak wajib pajak yang menjalankan kewajibannya, maka pendapatan asli daerah (PAD) dipastikan terdongkrak, sehingga hal ini tentu berimplikasi pada makin banyaknya pembangunan oleh pemerintah daerah yang pada gilirannya hasilnya pun dirasakan masyarakat.</div>', 'sosialisasi-perda-pajak-ajak-masyarakat-berkontribusi-bangun-daerah', 0, 1, '2022-12-15 08:26:59', '2022-12-15 08:26:59');");
        DB::insert("INSERT INTO `news` (`id`, `title`, `desc`, `slug`, `view`, `user_id`, `created_at`, `updated_at`) VALUES (6, 'EDUKASI MASYARAKAT TENTANG PAJAK DAERAH', '<div>SAMARINDA – Kepala Badan Pendapatan Daerah Prov Kaltim Ismiati mendampingi Ketua Komisi II Dewan Perwakilan Rakyat Daerah (DPRD) Kaltim Nidya Listiyono, melakukan Sosialisasi Peraturan Daerah di Samarinda. Kegiatan dilaksanakan di Angkringan Wijaya Kesuma, Minggu (31/7)</div><div>Sosialisasi tersebut diselenggarakan guna memberikan edukasi kepada masyarakat mengenai Perda Kaltim Nomor 1/2019 tentang Perubahan Kedua Atas Peraturan Daerah Nomor 1/2011 tentang Pajak Daerah.</div><div>Ismiati mengatakan, Pajak Daerah memberikan kontribusi cukup besar dalam Pendapatan Asli Daerah. Hingga akhir Juli, realisasinya mencapai 71,19 persen atau Rp 3,87 triliun dari target Rp 5,44 triliun.</div><div>“Pajak Daerah ini terdiri dari Pajak Kendaraan Bermotor (PKB), Bea Balik Nama Kendaraan Bermotor (BBNKB), Pajak Bahan Bakar Kendaraan Bermotor (PBBKB), Pajak Air Permukaan (PAP), dan Pajak Rokok,” papar Ismi.</div><div>Dalam proses pembayaran pajak, kata dia, Bapenda telah memberikan beragam kemudahan.</div><div>Selain memperluas jangkauan kantor layanan, Bapenda juga membuka jalur pembayaran baru memanfaatkan teknologi digital. Ismi menyebutkan layanan teranyar yakni E-Samsat Gojek, E-Samsat Tokopedia, E-Samsat Paykaltimtara, dan E-Dalam Genggaman Bhabin untuk pembayaran PKB.</div><div>“Dengan beragamnya layanan Bapenda, kami berharap masyarakat dapat taat membayarkan pajak,” sebut dia.</div><div>Sementara itu, Nidya menegaskan pentingnya masyarakat untuk membayar pajak dikarenakan penerimaan dari sektor itu nantinya juga akan digunakan untuk pembangunan daerah seperti pembangunan jalan, jembatan, dan infrastruktur lainnya.</div>', 'edukasi-masyarakat-tentang-pajak-daerah', 0, 1, '2022-12-15 08:28:51', '2022-12-15 08:28:51');");
        DB::insert("INSERT INTO `news` (`id`, `title`, `desc`, `slug`, `view`, `user_id`, `created_at`, `updated_at`) VALUES (7, 'TIM PEMBINA SAMSAT GELAR RAKOR PERSIAPAN RELAKSASI PAJAK 2022', '<div>BALIKPAPAN – Tim Pembina Samsat Kaltim yang terdiri dari Bapenda Prov Kaltim, Ditlantas Polda Kaltim, dan PT Jasa Raharja Cabang Kaltim menggelar Rapat Koordinasi Kesamsatan, Jumat (12/8).</div><div><br></div><div>Rapat membahas tentang persiapan pemberian relaksasi pajak yang akan berlangsung pada 16 Agustus sampai dengan 31 Oktober 2022. Persiapan dikoordinir langsung oleh Direktur Lalu Lintas Polda Kaltim Sonny Irawan.</div><div><br></div><div>Pada rapat tersebut Sonny mengarahkan seluruh jajarannya yakni seluruh Kasat Lantas dan Kanit Regident yang didukung Kasat/KBO Binmas dan seluruh petugas Bhabinkamtibmas se-Kaltim untuk menyosialisasikan program relaksasi.</div><div><br></div><div>Sementara untuk Tim Pembina Samsat Kaltim ia mengingatkan untuk terus meningkatkan komunikasi, koordinasi, dan kolaborasi.</div><div><br></div><div>“Sosialisasi yang terstruktur, sistematis, dan masif dirasa perlu dilakukan. Serta analisis dan evaluasi mingguan sebagai tolok ukur keberhasilan program ini,” ungkap Sonny bersama Kepala Bapenda Kaltim Hj Ismiati dan Kepala PT Jasa Raharja Cabang Kaltim Nasjwin.</div><div><br></div><div>Sementara itu, Kepala Bapenda Kaltim Hj Ismiati mengatakan tujuan relaksasi yakni mendorong percepatan pemulihan ekonomi dengan menstimulus pelaksanaan kewajiban pembayaran pajak kendaraan bermotor (PKB).</div><div><br></div><div>“Selain itu harapan kami dapat mengurangi piutang dan mendorong kendaraan luar daerah untuk mutasi ke wilayah Kaltim,” jelas Ismi.</div><div><br></div><div>Dia menjelaskan ada beberapa poin kebijakan yang diberlakukan sejak 16 Agustus sampai dengan 31 Oktober 2022 itu.</div><div><br></div><div>Pertama yaitu diskon 2 persen untuk pembayaran 0 s/d 30 hari sebelum jatuh tempo, diskon 4 persen untuk pembayaran 31 Hari s/d 60 hari sebelum jatuh tempo, dan diskon pokok PKB yang menunggak 4 tahun keatas, hanya membayar PKB terhitung 3 tahun.</div><div><br></div><div>Kemudian bebas denda administrasi, bebas pajak progresif, bebas BBNKB-II dan seterusnya. Serta pembebasan denda SWDKLLJ tahun sebelumnya.</div>', 'tim-pembina-samsat-gelar-rakor-persiapan-relaksasi-pajak-2022', 0, 1, '2022-12-15 08:30:12', '2022-12-15 08:30:12');");
        DB::insert("INSERT INTO `news` (`id`, `title`, `desc`, `slug`, `view`, `user_id`, `created_at`, `updated_at`) VALUES (8, 'MERIAHNYA BAPENDA CUP 2022', '<p style=\"margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; line-height: inherit; font-family: &quot;open sans&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(102, 102, 102);\">SAMARINDA – Tendangan ke gawang pertama kali oleh Kepala Bapenda Kaltim Hj Ismiati jadi penanda dibukanya Bapenda Cup 2022. Turnamen tersebut berlangsung di Lapangan Futsal Vivo, Jalan Kebaktian, Samarinda.</p><p style=\"margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; line-height: inherit; font-family: &quot;open sans&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(102, 102, 102);\">Keakraban nan seru jelas tergambar pada suasana kompetisi antar pegawai di lingkungan Bapenda tersebut.<br>“Bapenda Cup 2022 ini kami gelar untuk memeriahkan kemerdekaan Republik Indonesia. Pesertanya dari seluruh UPTD Pelayanan Pajak dan Retribusi Daerah se-Kaltim dan pegawai di Bapenda Provinsi,” kata Ismi.</p><p style=\"margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; line-height: inherit; font-family: &quot;open sans&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(102, 102, 102);\">Di babak final, UPTD PPRD Wilayah Balikpapan bersaing sengit melawan tim dari Bapenda Kaltim. Dengan skor 2-0, tim dari UPTD PPRD Wilayah Balikpapan keluar sebagai juara pertama.</p><p style=\"margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; line-height: inherit; font-family: &quot;open sans&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(102, 102, 102);\">Posisi runner up otomatis ditempati oleh tim dari Bapenda Kaltim sementara juara ketiga diraih oleh tim dari UPTD PPRD Wilayah Paser.</p>', 'meriahnya-bapenda-cup-2022', 0, 1, '2022-12-15 08:31:26', '2022-12-15 08:31:26');");
        DB::insert("INSERT INTO `news` (`id`, `title`, `desc`, `slug`, `view`, `user_id`, `created_at`, `updated_at`) VALUES (9, 'BAPENDA GELAR UPACARA HUT KE-77 RI', '<div>SAMARINDA – Badan Pendapatan Daerah Prov Kaltim menggelar upacara Hari Ulang Tahun Kemerdekaan ke-77 Republik Indonesia. Acara dilaksanakan di halaman Kantor Bapenda Kaltim, Jalan MT Haryono, Rabu (17/8).</div><div>Upacara bertema “Pulih Lebih Cepat, Bangkit Lebih Kuat” ini diikuti oleh seluruh pejabat struktural dan fungsional serta pegawai di lingkungan Bapenda Prov Kaltim dan UPTD PPRD Wilayah Samarinda.</div><div>Pada kesempatan itu, Kepala Bapenda Kaltim Hj Ismiati diwakili oleh Sekretaris Bapenda Kaltim H Anthoni Safarisa untuk bertindak sebagai inspektur upacara.</div><div><br></div>', 'bapenda-gelar-upacara-hut-ke-77-ri', 0, 1, '2022-12-15 08:32:38', '2022-12-15 08:32:38');");
        DB::insert("INSERT INTO `news` (`id`, `title`, `desc`, `slug`, `view`, `user_id`, `created_at`, `updated_at`) VALUES (10, 'Kabapenda Hadiri Jumpa Pers Gelaran Diskominfo Kaltim', '<div>SAMARINDA – Kepala Badan Pendapatan Daerah Prov Kaltim Hj Ismiati menemui awak media dalam Jumpa Pers di Ruang Warung Informasi Etam Kaltim (WIEK) Dinas Komunikasi dan Informasi (Diskominfo) Kaltim, Senin (22/8).</div><div>Kegiatan ini baru pertama kali digelar Diskominfo untuk mendekatkan Organisasi Perangkat Daerah (OPD) di lingkungan Pemprov Kaltim bersama media, baik cetak, online, radio, maupun televisi.</div><div>Kepala Diskominfo Kaltim HM Faisal mengatakan acara ini dibuat sebagai wadah mempertajam sosialisasi program milik OPD kepada media.</div><div>“Alhamdulillah saya lihat responsnya baik. Rencananya Jumpa Pers kami laksanakan sebulan sekali, namun dengan animo yang tinggi ini mungkin akan dua minggu sekali,” kata dia.</div><div>Kepala Bapenda Kaltim Hj Ismiati dalam kesempatan kali ini hadir didampingi Kabid Pajak Daerah Masudi Artha dan Kabid PPSIP Purwanto. Hadir pula Ketua Bidang Ekonomi, Sumber Daya Alam, dan Lingkungan Hidup TGUP3 Kaltim Dr Zulkarnain.</div><div>“Bapenda sangat senang bisa jadi yang pertama hadir menemui insan pers. Sesuai Undang-Undang (UU) Nomor 14/2008 tentang Keterbukaan Informasi Publik (KIP), kami pasti terbuka sesuai ketentuan,” ujar Ismiati.</div><div>Dalam kegiatan itu Ismi menyampaikan tentang Capaian Kinerja Bapenda. Dia juga menjelaskan beragam inovasi milik Bapenda</div><div>“Inovasi berguna agar masyarakat bisa membayar tepat waktu, mudah dan cepat tanpa harus datang ke palayanan samsat, hal ini untuk meningkatkan pelayanan bagi wajib pajak,” kata dia.</div>', 'kabapenda-hadiri-jumpa-pers-gelaran-diskominfo-kaltim', 0, 1, '2022-12-15 08:34:35', '2022-12-15 08:34:35');");
        DB::insert("INSERT INTO `news` (`id`, `title`, `desc`, `slug`, `view`, `user_id`, `created_at`, `updated_at`) VALUES (11, 'REALISASI DANA BAGI HASIL PAJAK PROVINSI KE KAB/KOTA CAPAI RP 2,14 TRILIUN', '<div>SAMARINDA – Badan Pendapatan Daerah Prov Kaltim menggelar rapat yang dihadiri seluruh Badan Pendapatan Daerah Kabupaten/Kota se-Kalimantan Timur di Kantor Bapenda Kaltim, Selasa (23/8).</div><div>Rapat digelar sebagai upaya optimalisasi penerimaan Pajak Daerah Prov Kaltim Tahun 2022 dan peningkatan penerimaan bagi hasil pajak daerah ke kab/kota se-Kaltim. Dalam rapat tersebut, Kepala Bapenda Kaltim Hj Ismiati menyampaikan capaian kinerja Bapenda.</div><div>Tentang Pajak Daerah, hingga Agustus 2022, telah mencapai Rp 4,04 triliun dari target Rp 5,44 triliun atau kini mencapai 74,26 persen.</div><div>Dia mengatakan, dari total pajak daerah tersebut terdapat dana bagi hasil pajak daerah yang disalurkan ke masing-masing kabupaten dan kota.</div><div>“Realisasi Bagi Hasil Pajak hingga Juli 2022 telah mencapai Rp 2,14 triliun atau 73 persen,” kata Ismi.</div><div>Proyeksi Bagi Hasil Pajak tahun anggaran 2022 pada APBD ditetapkan sebesar Rp 2,92 triliun dan bertambah menjadi Rp 3,20 triliun.</div><div>“Agar proyeksi ini tercapai kami berharap seluruh Bapenda Kabupaten dan Kota dapat membantu mengoptimalkan pajak daerah. Misalkan dengan membantu menyosialisasikan program terbaru kami yakni relaksasi pajak,” sebutnya.</div>', 'realisasi-dana-bagi-hasil-pajak-provinsi-ke-kab-kota-capai-rp-2-14-triliun', 0, 1, '2022-12-15 08:35:51', '2022-12-15 08:35:51');");
        DB::insert("INSERT INTO `news` (`id`, `title`, `desc`, `slug`, `view`, `user_id`, `created_at`, `updated_at`) VALUES (12, 'GUBERNUR : DBH EMAS HIJAU HARUS DIPERJUANGKAN', '<div>PALANGKA RAYA – Kelapa Sawit sebagai sebuah komoditas memang sangat memikat. Emas hijau ini jadi salah satu primadona sumber keuangan daerah.</div><div>Dalam kegiatan Borneo Forum ke-5 Tahun 2022 yang digelar Pemerintah Provinsi Kalimantan Tengah bersama pengusaha dan pelaku usaha perkebunan serta industri kelapa sawit di Kalimantan diangkat tema Perimbangan Anggaran Daerah untuk Komoditas Perkebunan Kelapa Sawit dan Turunannya.</div><div>Gubernur Kaltim Dr H Isran Noor mengakui kelapa sawit sangat besar kontribusinya bagi perekonomian dan pendapatan negara, bahkan mampu meningkatkan kesejahteraan rakyat termasuk di daerah.</div><div>Diacara yang dihadiri Deputi II Bidang Koordinasi Pangan dan Agribisnis Dr Musdhalifah Machmud, Sekjen Gapki Pusat Eddy Martono dan Presiden Borneo Forum Muhammadsjah Djafar, orang nomor satu Benua Etam ini kembali menegaskan kelapa sawit tetap harus memberikan kontribusi nyata bagi keuangan daerah untuk mendukung pembangunan.</div><div>Sebab yang terjadi saat ini menurut mantan Bupati Kutai Timur ini, pemerintah pusat memberlakukan dana bagi hasil (DBH) yang selisih nilainya pada 2020 hingga 2022 sebesar Rp40 triliun.</div><div>Khusus untuk sawit sebut Gubernur Isran, hanya ada sekitar Rp3,4 triliun yang akan dibagikan kepada daerah-daerah penghasil kelapa sawit.</div><div>“Nilai itu sangat kecil. Uang yang katanya DBH sebesar Rp3,4 triliun itu kecil dan tidak ada apa-apanya kalau harus dibagi-bagi ke daerah penghasil. Itu yang harus kita perjuangkan, DBH kelapa sawit yang pantas untuk daerah penghasil agar kita bisa membangun daerah,” pungkas mantan Ketua Apkasi ini.</div><div>Pada kesempatan ini Kepala Bapenda Kaltim Hj Ismiati dan Kepala Dinas Perkebunan Kaltim Ujang Rachmad turut hadir mendampingi Gubernur.</div><div>Borneo Forum digelar tiga hari (23-25 Agustus) mengangkat tema Menuju Industri Sawit Borneo Lebih Berkelanjutan diisi sambutan singkat Menko Perekomomian Airlangga Hartarto secara virtual.</div><div>📷 Biro Adpim Sekretariat Daerah Prov Kaltim</div>', 'gubernur-dbh-emas-hijau-harus-diperjuangkan', 0, 1, '2022-12-15 08:37:27', '2022-12-15 08:37:27');");
        DB::insert("INSERT INTO `news` (`id`, `title`, `desc`, `slug`, `view`, `user_id`, `created_at`, `updated_at`) VALUES (13, 'UNTUNG BERLIMPAH, BAYAR PAJAK DI KALTIM EXPO 2022', '<div>SAMARINDA – Kaltim Expo pada tahun ini kembali digelar selama lima hari (24-28 Agustus 2022). Badan Pendapatan Daerah Prov Kaltim pun ikut ambil bagian.</div><div>Expo kali ini dibuka oleh Staf Ahli Gubernur Bidang Sumber Daya Alam, Perekonomian Daerah dan Kesejahteraan Rakyat, Christianus Benny yang mewakili Gubernur Kaltim H Isran Noor.</div><div>Ia membuka kegiatan bersama Wakil Ketua Dekranasda Kaltim Erni Makmur dan Kepala Dinas Penanaman Modal Pelayanan Terpadu Satu Pintu (DPMPTSP) Kaltim Puguh Harjanto. Ketiganya pun mengunjungi booth milik Bapenda yang dihias meriah.</div><div>Di tempat terpisah, Kepala Bapenda Kaltim Hj Ismiati mengatakan masyarakat harus memanfaatkan momen berharga ini.</div><div>“Sebab untungnya berlimpah. Selain mendapatkan diskon pajak kendaraan dan bebas denda. Masyarakat bisa mendapatkan suvenir dan kesempatan meraih doorprize,” ucapnya.</div><div>Ada beragam hadiah yang telah disiapkan Bapenda. Mulai dari sepeda, televisi, kompor gas, dan lain-lain.</div><div>“Ayo bayar pajak di Kaltim Expo,” ajaknya.</div>', 'untung-berlimpah-bayar-pajak-di-kaltim-expo-2022', 0, 1, '2022-12-15 08:39:22', '2022-12-15 08:39:22');");
        DB::insert("INSERT INTO `news` (`id`, `title`, `desc`, `slug`, `view`, `user_id`, `created_at`, `updated_at`) VALUES (14, 'Talkshow Relaksasi Pajak Kabapenda : Ayo Manfaatkan Keuntungannya', '<div>SAMARINDA – Badan Pendapatan Daerah Prov Kaltim menggelar Talkshow Relaksasi Pajak yang menjadi satu rangkaian dalam kegiatan Kaltim Expo 2022 di Bigmall Samarinda, Sabtu (27/8).</div><div>Kepala Badan Pendapatan Daerah Prov Kaltim Hj Ismiati hadir sebagai pembicara dalam acara yang juga disiarkan langsung oleh Radio Republik Indonesia (RRI) Samarinda.</div><div>“Mewakili Pemprov Kaltim saya memberikan apresiasi yang tinggi kepada wajib pajak yang taat. Bagi yang belum membayarkan pajak, ayo segera manfaatkan keuntungannya sampai dengan 31 Oktober 2022,” ucap Ismi, sapaan akrabnya.</div><div>Dia menjelaskan ada beberapa poin kebijakan yang diberlakukan sejak 16 Agustus itu. Pertama yaitu diskon 2 persen untuk pembayaran 0 s/d 30 hari sebelum jatuh tempo, diskon 4 persen untuk pembayaran 31 Hari s/d 60 hari sebelum jatuh tempo, dan diskon pokok PKB yang menunggak 4 tahun keatas, hanya membayar PKB terhitung 3 tahun.</div><div>Kemudian bebas denda administrasi, bebas pajak progresif, bebas BBNKB-II dan</div><div>seterusnya. Serta pembebasan denda SWDKLLJ tahun sebelumnya.</div><div>“Khusus acara di Bigmall, besok juga kami akan mengundi Doorprize bagi wajib pajak yang beruntung yang membayar pajak di Booth Bapenda di Kaltim Expo. Ayo segera bayar pajak kendaraan Anda,” imbaunya.</div><div><br></div>', 'talkshow-relaksasi-pajak-kabapenda-ayo-manfaatkan-keuntungannya', 0, 1, '2022-12-15 08:40:28', '2022-12-15 08:40:28');");
        DB::insert("INSERT INTO `news` (`id`, `title`, `desc`, `slug`, `view`, `user_id`, `created_at`, `updated_at`) VALUES (15, 'GUBERNUR TUTUP KALTIM EXPO BAPENDA RAIH JUARA I STAND INFORMASI PUBLIK', '<div>SAMARINDA – Kaltim Expo 2022 resmi berakhir pada Minggu (28/8). Gubernur Kaltim H Isran Noor hadir untuk menutup kegiatan tersebut.</div><div>Orang nomor satu di Benua Etam itu mengaku senang ada banyak perkembangan dalam expo dari tahun ke tahun. “Mungkin pada tahun depan bisa dipikirkan untuk mengundang provinsi lain sebagai peserta expo agar semakin ramai,” tuturnya.</div><div>Sebelum menutup kegiatan dengan menabuh jimbe, Isran menyerahkan piala kepada stan-stan terpilih dengan beragam kategori. Badan Pendapatan Daerah Prov Kaltim tahun ini mendapatkan penghargaan Juara I Stan Informasi Publik.</div><div>Gubernur juga menyempatkan diri mencabut nomor undian doorprize dengan didampingi oleh Kepala Bapenda Kaltim Hj Ismiati dan Kepala Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu (DPMPTSP) Kaltim Puguh Harjanto.</div><div><br></div>', 'gubernur-tutup-kaltim-expo-bapenda-raih-juara-i-stand-informasi-publik', 0, 1, '2022-12-15 08:41:27', '2022-12-15 08:41:27');");
        DB::insert("INSERT INTO `news` (`id`, `title`, `desc`, `slug`, `view`, `user_id`, `created_at`, `updated_at`) VALUES (16, 'SERUNYA SOSIALISASI RELAKSASI PAJAK DI SMA 10 SAMARINDA', '<div>SAMARINDA – Sudah sepekan Badan Pendapatan Daerah Prov Kaltim melakukan sosialisasi Relaksasi Pajak Kendaraan Bermotor di beberapa pusat keramaian. Kali ini, Senin (29/8), sosialisasi dilakukan di SMA 10 Samarinda.</div><div>Dihadapan ribuan murid serta para guru, Kepala Bapenda Kaltim Hj Ismiati mengungkapkan tentang keuntungan membayar pajak. “Pertama, jika membayar pajak tepat waktu otomatis dia sudah menjadi pahlawan. Karena dengan membayar pajak dia telah memberikan banyak manfaat bagi sesama,” jelasnya didampingi Kepala SMA 10 Samarinda Suharno.</div><div>Ismi, sapaan akrabnya, menerangkan jika dana pajak yang terkumpul akan disalurkan kembali untuk rakyat. Di antaranya untuk kebutuhan pendidikan, kesehatan, dan pelayanan umum lainnya.</div><div>Adapun mengenai relaksasi pajak, dia menjelaskan ada beberapa poin kebijakan yang diberlakukan sejak 16 Agustus sampai dengan 31 Oktober 2022 itu. Pertama yaitu diskon 2 persen untuk pembayaran 0 s/d 30 hari sebelum jatuh tempo, diskon 4 persen untuk pembayaran 31 Hari s/d 60 hari sebelum jatuh tempo, dan diskon pokok PKB yang menunggak 4 tahun keatas, hanya membayar PKB terhitung 3 tahun.</div><div>Kemudian bebas denda administrasi, bebas pajak progresif, bebas BBNKB-II dan seterusnya. Serta pembebasan denda SWDKLLJ tahun sebelumnya.</div><div>“Saya berharap para guru dan murid yang memiliki kendaraan di sini adalah wajib pajak yang taat. Supaya mudah, nanti saya kirim Samsat Keliling untuk mampir ke sekolah. Ayo manfaatkan relaksasi pajak,” kata Ismi.</div><div>Bapenda Kaltim juga memberikan hadiah berupa bingkisan menarik bagi para murid yang beruntung.</div>', 'serunya-sosialisasi-relaksasi-pajak-di-sma-10-samarinda', 0, 1, '2022-12-15 08:42:55', '2022-12-15 08:42:55');");

        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (1, 'news-images/news1-1.jpg', 1, '2022-12-15 08:22:02', '2022-12-15 08:22:02');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (2, 'news-images/news1-2.jpg', 1, '2022-12-15 08:22:02', '2022-12-15 08:22:02');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (3, 'news-images/news1-3.jpg', 1, '2022-12-15 08:22:02', '2022-12-15 08:22:02');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (4, 'news-images/news1-4.jpg', 1, '2022-12-15 08:22:02', '2022-12-15 08:22:02');");

        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (5, 'news-images/news2-1.jpg', 2, '2022-12-15 08:23:22', '2022-12-15 08:23:22');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (6, 'news-images/news2-2.jpg', 2, '2022-12-15 08:23:22', '2022-12-15 08:23:22');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (7, 'news-images/news2-3.jpg', 2, '2022-12-15 08:23:22', '2022-12-15 08:23:22');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (8, 'news-images/news2-4.jpg', 2, '2022-12-15 08:23:22', '2022-12-15 08:23:22');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (9, 'news-images/news2-5.jpg', 2, '2022-12-15 08:23:22', '2022-12-15 08:23:22');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (10, 'news-images/news2-6.jpg', 2, '2022-12-15 08:23:22', '2022-12-15 08:23:22');");

        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (11, 'news-images/news3-1.jpg', 3, '2022-12-15 08:24:25', '2022-12-15 08:24:25');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (12, 'news-images/news3-2.jpg', 3, '2022-12-15 08:24:25', '2022-12-15 08:24:25');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (13, 'news-images/news3-3.jpg', 3, '2022-12-15 08:24:25', '2022-12-15 08:24:25');");

        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (14, 'news-images/news4-1.jpg', 4, '2022-12-15 08:25:52', '2022-12-15 08:25:52');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (15, 'news-images/news4-2.jpg', 4, '2022-12-15 08:25:52', '2022-12-15 08:25:52');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (16, 'news-images/news4-3.jpg', 4, '2022-12-15 08:25:52', '2022-12-15 08:25:52');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (17, 'news-images/news4-4.jpg', 4, '2022-12-15 08:25:52', '2022-12-15 08:25:52');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (18, 'news-images/news4-5.jpg', 4, '2022-12-15 08:25:52', '2022-12-15 08:25:52');");

        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (19, 'news-images/news5-1.jpg', 5, '2022-12-15 08:26:59', '2022-12-15 08:26:59');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (20, 'news-images/news5-2.jpg', 5, '2022-12-15 08:26:59', '2022-12-15 08:26:59');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (21, 'news-images/news5-3.jpg', 5, '2022-12-15 08:26:59', '2022-12-15 08:26:59');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (22, 'news-images/news5-4.jpg', 5, '2022-12-15 08:26:59', '2022-12-15 08:26:59');");

        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (23, 'news-images/news6-1.jpg', 6, '2022-12-15 08:28:51', '2022-12-15 08:28:51');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (24, 'news-images/news6-2.jpg', 6, '2022-12-15 08:28:51', '2022-12-15 08:28:51');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (25, 'news-images/news6-3.jpg', 6, '2022-12-15 08:28:51', '2022-12-15 08:28:51');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (26, 'news-images/news6-4.jpg', 6, '2022-12-15 08:28:51', '2022-12-15 08:28:51');");

        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (27, 'news-images/news7-1.jpg', 7, '2022-12-15 08:30:12', '2022-12-15 08:30:12');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (28, 'news-images/news7-2.jpg', 7, '2022-12-15 08:30:12', '2022-12-15 08:30:12');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (29, 'news-images/news7-3.jpg', 7, '2022-12-15 08:30:12', '2022-12-15 08:30:12');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (30, 'news-images/news7-4.jpg', 7, '2022-12-15 08:30:12', '2022-12-15 08:30:12');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (31, 'news-images/news7-5.jpg', 7, '2022-12-15 08:30:12', '2022-12-15 08:30:12');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (32, 'news-images/news7-6.jpg', 7, '2022-12-15 08:30:12', '2022-12-15 08:30:12');");

        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (33, 'news-images/news8-1.jpg', 8, '2022-12-15 08:31:26', '2022-12-15 08:31:26');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (34, 'news-images/news8-2.jpg', 8, '2022-12-15 08:31:26', '2022-12-15 08:31:26');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (35, 'news-images/news8-3.jpg', 8, '2022-12-15 08:31:26', '2022-12-15 08:31:26');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (36, 'news-images/news8-4.jpg', 8, '2022-12-15 08:31:26', '2022-12-15 08:31:26');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (37, 'news-images/news8-5.jpg', 8, '2022-12-15 08:31:26', '2022-12-15 08:31:26');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (38, 'news-images/news8-6.jpg', 8, '2022-12-15 08:31:26', '2022-12-15 08:31:26');");

        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (39, 'news-images/news9-1.jpg', 9, '2022-12-15 08:32:38', '2022-12-15 08:32:38');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (40, 'news-images/news9-2.jpg', 9, '2022-12-15 08:32:38', '2022-12-15 08:32:38');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (41, 'news-images/news9-3.jpg', 9, '2022-12-15 08:32:38', '2022-12-15 08:32:38');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (42, 'news-images/news9-4.jpg', 9, '2022-12-15 08:32:38', '2022-12-15 08:32:38');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (43, 'news-images/news9-5.jpg', 9, '2022-12-15 08:32:38', '2022-12-15 08:32:38');");

        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (44, 'news-images/news10-1.jpg', 10, '2022-12-15 08:34:35', '2022-12-15 08:34:35');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (45, 'news-images/news10-2.jpg', 10, '2022-12-15 08:34:35', '2022-12-15 08:34:35');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (46, 'news-images/news10-3.jpg', 10, '2022-12-15 08:34:35', '2022-12-15 08:34:35');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (47, 'news-images/news10-4.jpg', 10, '2022-12-15 08:34:35', '2022-12-15 08:34:35');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (48, 'news-images/news10-5.jpg', 10, '2022-12-15 08:34:35', '2022-12-15 08:34:35');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (49, 'news-images/news10-6.jpg', 10, '2022-12-15 08:34:35', '2022-12-15 08:34:35');");

        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (50, 'news-images/news11-1.jpg', 11, '2022-12-15 08:35:51', '2022-12-15 08:35:51');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (51, 'news-images/news11-2.jpg', 11, '2022-12-15 08:35:51', '2022-12-15 08:35:51');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (52, 'news-images/news11-3.jpg', 11, '2022-12-15 08:35:51', '2022-12-15 08:35:51');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (53, 'news-images/news11-4.jpg', 11, '2022-12-15 08:35:51', '2022-12-15 08:35:51');");

        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (54, 'news-images/news12-1.jpg', 12, '2022-12-15 08:37:27', '2022-12-15 08:37:27');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (55, 'news-images/news12-2.jpg', 12, '2022-12-15 08:37:27', '2022-12-15 08:37:27');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (56, 'news-images/news12-3.jpg', 12, '2022-12-15 08:37:27', '2022-12-15 08:37:27');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (57, 'news-images/news12-4.jpg', 12, '2022-12-15 08:37:27', '2022-12-15 08:37:27');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (58, 'news-images/news12-5.jpg', 12, '2022-12-15 08:37:27', '2022-12-15 08:37:27');");

        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (59, 'news-images/news13-1.jpg', 13, '2022-12-15 08:39:22', '2022-12-15 08:39:22');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (60, 'news-images/news13-2.jpg', 13, '2022-12-15 08:39:22', '2022-12-15 08:39:22');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (61, 'news-images/news13-3.jpg', 13, '2022-12-15 08:39:22', '2022-12-15 08:39:22');");

        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (62, 'news-images/news14-1.jpg', 14, '2022-12-15 08:40:28', '2022-12-15 08:40:28');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (63, 'news-images/news14-2.jpg', 14, '2022-12-15 08:40:28', '2022-12-15 08:40:28');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (64, 'news-images/news14-3.jpg', 14, '2022-12-15 08:40:28', '2022-12-15 08:40:28');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (65, 'news-images/news14-4.jpg', 14, '2022-12-15 08:40:28', '2022-12-15 08:40:28');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (66, 'news-images/news14-5.jpg', 14, '2022-12-15 08:40:28', '2022-12-15 08:40:28');");

        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (67, 'news-images/news15-1.jpg', 15, '2022-12-15 08:41:27', '2022-12-15 08:41:27');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (68, 'news-images/news15-2.jpg', 15, '2022-12-15 08:41:27', '2022-12-15 08:41:27');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (69, 'news-images/news15-3.jpg', 15, '2022-12-15 08:41:27', '2022-12-15 08:41:27');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (70, 'news-images/news15-4.jpg', 15, '2022-12-15 08:41:27', '2022-12-15 08:41:27');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (71, 'news-images/news15-5.jpg', 15, '2022-12-15 08:41:27', '2022-12-15 08:41:27');");

        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (72, 'news-images/news16-1.jpg', 16, '2022-12-15 08:42:55', '2022-12-15 08:42:55');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (73, 'news-images/news16-2.jpg', 16, '2022-12-15 08:42:55', '2022-12-15 08:42:55');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (74, 'news-images/news16-3.jpg', 16, '2022-12-15 08:42:55', '2022-12-15 08:42:55');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (75, 'news-images/news16-4.jpg', 16, '2022-12-15 08:42:55', '2022-12-15 08:42:55');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (76, 'news-images/news16-5.jpg', 16, '2022-12-15 08:42:55', '2022-12-15 08:42:55');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (77, 'news-images/news16-6.jpg', 16, '2022-12-15 08:42:55', '2022-12-15 08:42:55');");
        DB::insert("INSERT INTO `news_galleries` (`id`, `img`, `news_id`, `created_at`, `updated_at`) VALUES (78, 'news-images/news16-7.jpg', 16, '2022-12-15 08:42:55', '2022-12-15 08:42:55');");
    }
}
